name: Deploy to Vercel
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_npYHmvkxw24mzr8AbquLeNxHnkEb/RLs3GyRout
